# Generated by Django 5.1.4 on 2025-10-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='UserName',
        ),
    ]
